/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatbot;


import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;



/**
 *
 * @author Regson
 */
public class Janela extends javax.swing.JFrame  {

    /**
     * Creates new form Janela
     */
    
    public ChatBot cb=new ChatBot();
   // public JLabel lbImagem=new JLabel();
  

    public Janela() {
        initComponents();
        this.setTitle("Betta - Chatbot Lanchonete - Java v0.5");
        
        // gera uma frase de apresentação ao iniciar o programa
        
        
        //mudando a imagem
        this.lbImagem.setIcon(new ImageIcon("img//imagemHappy.jpg"));

        this.txtEntrada.addKeyListener(
            new KeyListener()
            {
                    
                @Override
                public void keyReleased(KeyEvent e){
                    
                    
                    if(e.getKeyCode() == KeyEvent.VK_ENTER)
                    {

                        Thread t = new Thread(new Runnable() {
                        public void run()
                        {
                                cb.executaIA();
                               
                                 try{
                                   Thread.sleep(3000);
                                }
                                catch(InterruptedException ie)
                                {
                    
                                }
                                 
                                lbImagem.setIcon(new ImageIcon("img//imagemNormal.jpg"));
                                lbImagem.repaint();
                        }
                        });
                      
                        t.start();
                        
                        
                    }       
            }

            @Override
            public void keyTyped(KeyEvent ke) {
            }

            @Override
            public void keyPressed(KeyEvent ke) {
            }

        }); //end keyListener
        
       
    }
   
    


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEntrada = new javax.swing.JTextField();
        lbSaida = new javax.swing.JLabel();
        lbImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TictacKode - Chatbot Lanchonete v0.3");

        txtEntrada.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        lbSaida.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbSaida.setForeground(new java.awt.Color(51, 51, 255));
        lbSaida.setToolTipText("");

        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatbot/imagemHappy.jpg"))); // NOI18N
        lbImagem.setLabelFor(lbImagem);
        lbImagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                update(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addComponent(lbSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void update(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_update
        // TODO add your handling code here:
       // this.lbImagem=new JLabel(this.cb.GD.imagemAtual);
    }//GEN-LAST:event_update
    
  
    public void falaBot(String textoFala)
    {
        
        
        
         Thread t = new Thread(new Runnable() {
                        
            public void run()
            {
                               
                String aux="";            
               for(int i=0;i<textoFala.length();i++)
               {
                        aux=aux.concat(textoFala.substring(i,i+1));
                        lbSaida.setText(aux);
                        lbSaida.repaint();
                   try{
                            Thread.sleep(40);
                      }
                        catch(InterruptedException ie){
                        }

               }
                              
            }                 
                               
                });
        
        t.start();
        
      

        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lbImagem;
    public javax.swing.JLabel lbSaida;
    public javax.swing.JTextField txtEntrada;
    // End of variables declaration//GEN-END:variables
}
